# Generated by Django 4.2 on 2024-05-14 22:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='flan',
            old_name='desription',
            new_name='description',
        ),
    ]
