# Generated by Django 4.2 on 2024-05-23 01:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_contactform'),
    ]

    operations = [
        migrations.CreateModel(
            name='Receta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ingredientes', models.TextField()),
                ('preparacion', models.TextField()),
                ('flan', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='receta', to='web.flan')),
            ],
        ),
    ]
