# Generated by Django 4.2 on 2024-05-23 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_flan_ingredients_flan_preparation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='flan',
            name='ingredients_description',
            field=models.TextField(default='no especificado'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='flan',
            name='preparation_description',
            field=models.TextField(default='no especificado'),
            preserve_default=False,
        ),
    ]
